### ISSUE TITLE
Issue: Tooltip doesn't follow the anchored view position.

### ISSUE THREAD

**Issue by emanzanoaxa** [spyhunter99/supertooltips#4]
When the view wich the tooltip is anchored to moves (for example if the view is inside a NestedScrollView), the tooltip view remains on the same position.

**Comment by spyhunter99** [comment]
hmm never tried it, works ok for list view items.

**Comment by renclav** [comment]
same

**Comment by spyhunter99** [comment]
@renclav @emanzanoaxa do either of you have a test case that i can use to experiment with?

**Comment by renclav** [comment]
aah, so I resolved this bug. Don't think it's a library issue.
I just moved ToolTipRelativeLayout to a lower level in the layout. I assumed it was due to a parent issue.

Example (Broken)
```
<LinearLayout
 <NestedScrollView
  <FrameLayout
   <LinearLayout
   -anchored view-
     LinearLayout>
    FrameLayout>
   NestedScrollView>
<ToolTipRelativeLayout>
  LinearLayout>
```

just moving ToolTipRelativeLayout into the FrameLayout inside the NestedScrollView resolved the issue

**Comment by spyhunter99** [comment]
roger that, thanks for the report @renclav
