### ISSUE TITLE
NullpointerException if close is called before tooltip is fully initialized

### ISSUE THREAD

**Issue by tobiasschuerg** [spyhunter99/supertooltips#5]
If a tooltip is set and closed before the view is set up again, a NullpointerException occurs.

```
   tooltips.showToolTip(toolTip, view);
   tooltips.closeActiveTooltip();
```

results into

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                     Process PID: 23851
>                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
>                                                                         at com.spyhunter99.supertooltips.ToolTipView.onPreDraw(ToolTipView.java:122)
>                                                                         at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
> etc ...

**Comment by spyhunter99** [comment]
awesome, thanks for the report

**Comment by spyhunter99** [comment]
added a fix and a way to test it.

**Comment by spyhunter99** [comment]
@tobiasschuerg if you have time and are able to do so, please test, otherwise i'll just cut the release, probably this weekend

**Comment by tobiasschuerg** [comment]
@spyhunter99 thanks for the quick fix. However this only solves the exception to be thrown but there will then be an ugly *dismiss*-animation.

**Comment by tobiasschuerg** [comment]
This avoids the animation if the view is not set up completely: https://github.com/tobiasschuerg/supertooltips/commit/8292fe0352787c780d2bdff8daa212b85df6bb20

Maybe this could even be solved in a nicer fashion?

**Comment by spyhunter99** [comment]
hmm looking at it now

**Comment by spyhunter99** [comment]
your solution looks like it's probably the best for the timing being. i tried attempting to remove from parent, but this case it caused an infinite loop

**Comment by spyhunter99** [comment]
thanks for looking into this!

**Comment by tobiasschuerg** [comment]
@spyhunter99 can you please release a new version which includes this fix?

**Comment by spyhunter99** [comment]
Sure thing

**Comment by spyhunter99** [comment]
Verion 4.0.1 is cut, it may take a day or two before it's available
globally on all maven central mirrors
