### ISSUE TITLE
How to close this on clicking outside?

### ISSUE THREAD

**Issue by talk2cerlin** [spyhunter99/supertooltips#6]
I wanted to close the tooltip by clicking outside of the tooltip. Is there anyway i can do that?

**Comment by spyhunter99** [comment]
Well, there is ToolTipManager.destroy and ToolTipManager.tooltips.closeActiveTooltip();
does that work for you?

**Comment by talk2cerlin** [comment]
For closing the popup i can use that but now to detect the click outside, i will have to put a dummy view outside by filling the parent and read clicks on that. 

I was wondering if the plugin handles that for us.

**Comment by spyhunter99** [comment]
no sorry. it may be possible with a focus/focus lost if that's something android provides
