### ISSUE TITLE
Tooltip Adaptative

### ISSUE THREAD

**Issue by manucodin** [spyhunter99/supertooltips#7]
Hi, when I use a tooltip of your library and put text inside him. The text appears in two lines, for example...if I write "house", appear in the first line "hous" and in the second line "e".  How I can do if I  want the text appear in only one line? Thanx

**Comment by spyhunter99** [comment]
that's really strange. The sample app does not do this. Can you provide code to reproduce?

**Comment by manucodin** [comment]
No sorry, but you use some constraint with the parent element? I think that the problem maybe is this

**Comment by manucodin** [comment]
![screenshot_20170416-005427](https://cloud.githubusercontent.com/assets/15260744/25067315/9370c762-223f-11e7-9234-bebbc93c8444.png)

**Comment by spyhunter99** [comment]
Ahh that could be it. I'm not the original author actually. I forked
someone else's fork. Fixing a bunch of problems along the way and published
it to central. I'll take a quick look at it.

**Comment by spyhunter99** [comment]
the view that was clicked, what type is it? a image button perhaps?

**Comment by manucodin** [comment]
Its a image view, when the image view use wrap content size the tooltip appear correctly, but when I give it some size (58dp x 58dp) it does not
